@startuml
title Admin Management Activity Diagram
skinparam shadowing false
skinparam linetype ortho

|Admin|
start
:Log In;

while (Keep Session Active?) is (Yes)
  switch (Choose Action)
  case (Manage Users)
    :Manage Users & Roles;
  case (Manage Topics)
    :Manage Global Topic List;
  case (Manage Policies)
    :Configure Policies/Templates;
  endswitch
endwhile (No, Log Out)

:Log Out;
stop
@enduml
