@startuml
title Rating Analytics Activity Diagram
skinparam shadowing false
skinparam linetype ortho

|Author|
start
:Access Reviewer Ratings Form;
note right: Only available after\nReviewer submits Feedback.

fork
  :Rate Quality (1-5);
fork again
  :Rate Quantity (1-5);
fork again
  :Rate Timeliness (1-5);
end fork

|System|
:Calculate Aggregate Score;
:Update Reviewer Global Ranking;

stop
@enduml
